// Mocks generated by Mockito 5.4.6 from annotations
// in new_words/test/dio_interceptors/auth_interceptor_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:new_words/common/foundation/foundation.dart' as _i5;
import 'package:new_words/entities/user.dart' as _i2;
import 'package:new_words/services/account_service_v2.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeUser_0 extends _i1.SmartFake implements _i2.User {
  _FakeUser_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFuture_1<T1> extends _i1.SmartFake implements _i3.Future<T1> {
  _FakeFuture_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AccountServiceV2].
///
/// See the documentation for Mockito's code generation for more information.
class MockAccountServiceV2 extends _i1.Mock implements _i4.AccountServiceV2 {
  MockAccountServiceV2() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> login(String? email, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#login, [email, password]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> register(
    String? email,
    String? password,
    String? nativeLanguage,
    String? learningLanguage,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#register, [
              email,
              password,
              nativeLanguage,
              learningLanguage,
            ]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<_i2.User> getMyInformation() =>
      (super.noSuchMethod(
            Invocation.method(#getMyInformation, []),
            returnValue: _i3.Future<_i2.User>.value(
              _FakeUser_0(this, Invocation.method(#getMyInformation, [])),
            ),
          )
          as _i3.Future<_i2.User>);

  @override
  _i3.Future<void> changePassword(
    String? currentPassword,
    String? newPassword,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#changePassword, [currentPassword, newPassword]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateUserLanguages(
    String? nativeLanguage,
    String? learningLanguage,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateUserLanguages, [
              nativeLanguage,
              learningLanguage,
            ]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteAccount() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAccount, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<String?> getToken() =>
      (super.noSuchMethod(
            Invocation.method(#getToken, []),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  bool hasValidToken() =>
      (super.noSuchMethod(
            Invocation.method(#hasValidToken, []),
            returnValue: false,
          )
          as bool);

  @override
  _i3.Future<bool> isValidToken() =>
      (super.noSuchMethod(
            Invocation.method(#isValidToken, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<void> setUserSession({String? tokenFromInit}) =>
      (super.noSuchMethod(
            Invocation.method(#setUserSession, [], {
              #tokenFromInit: tokenFromInit,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  T processResponse<T>(_i5.ApiResponseV2<T>? response) =>
      (super.noSuchMethod(
            Invocation.method(#processResponse, [response]),
            returnValue: _i6.dummyValue<T>(
              this,
              Invocation.method(#processResponse, [response]),
            ),
          )
          as T);

  @override
  void processVoidResponse(_i5.ApiResponseV2<void>? response) =>
      super.noSuchMethod(
        Invocation.method(#processVoidResponse, [response]),
        returnValueForMissingStub: null,
      );

  @override
  T processResponseWithCustomError<T>(
    _i5.ApiResponseV2<T>? response,
    _i5.ServiceException Function(String?, int?, int?)? errorFactory,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#processResponseWithCustomError, [
              response,
              errorFactory,
            ]),
            returnValue: _i6.dummyValue<T>(
              this,
              Invocation.method(#processResponseWithCustomError, [
                response,
                errorFactory,
              ]),
            ),
          )
          as T);

  @override
  _i3.Future<T> safeApiCall<T>(_i3.Future<_i5.ApiResponseV2<T>>? apiCall) =>
      (super.noSuchMethod(
            Invocation.method(#safeApiCall, [apiCall]),
            returnValue:
                _i6.ifNotNull(
                  _i6.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#safeApiCall, [apiCall]),
                  ),
                  (T v) => _i3.Future<T>.value(v),
                ) ??
                _FakeFuture_1<T>(
                  this,
                  Invocation.method(#safeApiCall, [apiCall]),
                ),
          )
          as _i3.Future<T>);

  @override
  _i3.Future<void> safeVoidApiCall(
    _i3.Future<_i5.ApiResponseV2<void>>? apiCall,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#safeVoidApiCall, [apiCall]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  R transformData<T, R>(
    T? data,
    R Function(T)? transformer, {
    String? operationName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #transformData,
              [data, transformer],
              {#operationName: operationName},
            ),
            returnValue: _i6.dummyValue<R>(
              this,
              Invocation.method(
                #transformData,
                [data, transformer],
                {#operationName: operationName},
              ),
            ),
          )
          as R);

  @override
  void validateInput(Map<String, dynamic>? validations) => super.noSuchMethod(
    Invocation.method(#validateInput, [validations]),
    returnValueForMissingStub: null,
  );

  @override
  void validateStringField(
    String? value,
    String? fieldName, {
    int? minLength,
    int? maxLength,
    bool? required = true,
    Pattern? pattern,
    String? patternDescription,
  }) => super.noSuchMethod(
    Invocation.method(
      #validateStringField,
      [value, fieldName],
      {
        #minLength: minLength,
        #maxLength: maxLength,
        #required: required,
        #pattern: pattern,
        #patternDescription: patternDescription,
      },
    ),
    returnValueForMissingStub: null,
  );

  @override
  void validateNumericField(
    num? value,
    String? fieldName, {
    num? min,
    num? max,
    bool? required = true,
  }) => super.noSuchMethod(
    Invocation.method(
      #validateNumericField,
      [value, fieldName],
      {#min: min, #max: max, #required: required},
    ),
    returnValueForMissingStub: null,
  );

  @override
  Map<String, dynamic> processPaginationParams(
    int? pageNumber,
    int? pageSize, {
    int? maxPageSize = 100,
    int? minPageSize = 1,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #processPaginationParams,
              [pageNumber, pageSize],
              {#maxPageSize: maxPageSize, #minPageSize: minPageSize},
            ),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  String createErrorMessage(String? operation, String? details) =>
      (super.noSuchMethod(
            Invocation.method(#createErrorMessage, [operation, details]),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.method(#createErrorMessage, [operation, details]),
            ),
          )
          as String);

  @override
  void logOperation(String? operation, {Map<String, dynamic>? parameters}) =>
      super.noSuchMethod(
        Invocation.method(
          #logOperation,
          [operation],
          {#parameters: parameters},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void logError(String? operation, _i5.ServiceException? error) =>
      super.noSuchMethod(
        Invocation.method(#logError, [operation, error]),
        returnValueForMissingStub: null,
      );
}
