// Mocks generated by Mockito 5.4.6 from annotations
// in new_words/test/providers/subscription_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:in_app_purchase/in_app_purchase.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:new_words/entities/purchase_result.dart' as _i4;
import 'package:new_words/entities/subscription_tier.dart' as _i6;
import 'package:new_words/services/subscription_service.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [SubscriptionService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSubscriptionService extends _i1.Mock
    implements _i2.SubscriptionService {
  MockSubscriptionService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<_i4.PurchaseResult> get purchaseStream =>
      (super.noSuchMethod(
            Invocation.getter(#purchaseStream),
            returnValue: _i3.Stream<_i4.PurchaseResult>.empty(),
          )
          as _i3.Stream<_i4.PurchaseResult>);

  @override
  _i3.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i5.ProductDetails>> getAvailableProducts() =>
      (super.noSuchMethod(
            Invocation.method(#getAvailableProducts, []),
            returnValue: _i3.Future<List<_i5.ProductDetails>>.value(
              <_i5.ProductDetails>[],
            ),
          )
          as _i3.Future<List<_i5.ProductDetails>>);

  @override
  _i3.Future<void> purchaseSubscription(_i6.SubscriptionTier? tier) =>
      (super.noSuchMethod(
            Invocation.method(#purchaseSubscription, [tier]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> restorePurchases() =>
      (super.noSuchMethod(
            Invocation.method(#restorePurchases, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i5.PurchaseDetails>> getPastPurchases() =>
      (super.noSuchMethod(
            Invocation.method(#getPastPurchases, []),
            returnValue: _i3.Future<List<_i5.PurchaseDetails>>.value(
              <_i5.PurchaseDetails>[],
            ),
          )
          as _i3.Future<List<_i5.PurchaseDetails>>);

  @override
  _i3.Future<bool> verifyPurchase(_i5.PurchaseDetails? purchase) =>
      (super.noSuchMethod(
            Invocation.method(#verifyPurchase, [purchase]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}
