// Mocks generated by Mockito 5.4.6 from annotations
// in new_words/test/providers/vocabulary_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:new_words/common/foundation/foundation.dart' as _i9;
import 'package:new_words/entities/add_word_request.dart' as _i7;
import 'package:new_words/entities/explanations_response.dart' as _i5;
import 'package:new_words/entities/page_data.dart' as _i3;
import 'package:new_words/entities/word_explanation.dart' as _i2;
import 'package:new_words/services/vocabulary_service_v2.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeWordExplanation_0 extends _i1.SmartFake
    implements _i2.WordExplanation {
  _FakeWordExplanation_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePageData_1<T> extends _i1.SmartFake implements _i3.PageData<T> {
  _FakePageData_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRefreshExplanationResult_2 extends _i1.SmartFake
    implements _i4.RefreshExplanationResult {
  _FakeRefreshExplanationResult_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeExplanationsResponse_3 extends _i1.SmartFake
    implements _i5.ExplanationsResponse {
  _FakeExplanationsResponse_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFuture_4<T1> extends _i1.SmartFake implements _i6.Future<T1> {
  _FakeFuture_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [VocabularyServiceV2].
///
/// See the documentation for Mockito's code generation for more information.
class MockVocabularyServiceV2 extends _i1.Mock
    implements _i4.VocabularyServiceV2 {
  MockVocabularyServiceV2() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.WordExplanation> addWord(_i7.AddWordRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#addWord, [request]),
            returnValue: _i6.Future<_i2.WordExplanation>.value(
              _FakeWordExplanation_0(
                this,
                Invocation.method(#addWord, [request]),
              ),
            ),
          )
          as _i6.Future<_i2.WordExplanation>);

  @override
  _i6.Future<_i3.PageData<_i2.WordExplanation>> listWords(
    int? pageNumber,
    int? pageSize,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#listWords, [pageNumber, pageSize]),
            returnValue: _i6.Future<_i3.PageData<_i2.WordExplanation>>.value(
              _FakePageData_1<_i2.WordExplanation>(
                this,
                Invocation.method(#listWords, [pageNumber, pageSize]),
              ),
            ),
          )
          as _i6.Future<_i3.PageData<_i2.WordExplanation>>);

  @override
  _i6.Future<void> deleteWord(int? wordId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteWord, [wordId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i4.RefreshExplanationResult> refreshExplanation(
    _i2.WordExplanation? explanation,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#refreshExplanation, [explanation]),
            returnValue: _i6.Future<_i4.RefreshExplanationResult>.value(
              _FakeRefreshExplanationResult_2(
                this,
                Invocation.method(#refreshExplanation, [explanation]),
              ),
            ),
          )
          as _i6.Future<_i4.RefreshExplanationResult>);

  @override
  _i6.Future<List<_i2.WordExplanation>> getMemories(String? localTimezone) =>
      (super.noSuchMethod(
            Invocation.method(#getMemories, [localTimezone]),
            returnValue: _i6.Future<List<_i2.WordExplanation>>.value(
              <_i2.WordExplanation>[],
            ),
          )
          as _i6.Future<List<_i2.WordExplanation>>);

  @override
  _i6.Future<List<_i2.WordExplanation>> getMemoriesOnDate(
    String? localTimezone,
    String? yyyyMMdd,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getMemoriesOnDate, [localTimezone, yyyyMMdd]),
            returnValue: _i6.Future<List<_i2.WordExplanation>>.value(
              <_i2.WordExplanation>[],
            ),
          )
          as _i6.Future<List<_i2.WordExplanation>>);

  @override
  _i6.Future<_i5.ExplanationsResponse> getExplanationsForWord(
    int? wordCollectionId,
    String? learningLanguage,
    String? explanationLanguage,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getExplanationsForWord, [
              wordCollectionId,
              learningLanguage,
              explanationLanguage,
            ]),
            returnValue: _i6.Future<_i5.ExplanationsResponse>.value(
              _FakeExplanationsResponse_3(
                this,
                Invocation.method(#getExplanationsForWord, [
                  wordCollectionId,
                  learningLanguage,
                  explanationLanguage,
                ]),
              ),
            ),
          )
          as _i6.Future<_i5.ExplanationsResponse>);

  @override
  _i6.Future<void> switchDefaultExplanation(
    int? wordCollectionId,
    int? explanationId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#switchDefaultExplanation, [
              wordCollectionId,
              explanationId,
            ]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  String createErrorMessage(String? operation, String? details) =>
      (super.noSuchMethod(
            Invocation.method(#createErrorMessage, [operation, details]),
            returnValue: _i8.dummyValue<String>(
              this,
              Invocation.method(#createErrorMessage, [operation, details]),
            ),
          )
          as String);

  @override
  T processResponse<T>(_i9.ApiResponseV2<T>? response) =>
      (super.noSuchMethod(
            Invocation.method(#processResponse, [response]),
            returnValue: _i8.dummyValue<T>(
              this,
              Invocation.method(#processResponse, [response]),
            ),
          )
          as T);

  @override
  void processVoidResponse(_i9.ApiResponseV2<void>? response) =>
      super.noSuchMethod(
        Invocation.method(#processVoidResponse, [response]),
        returnValueForMissingStub: null,
      );

  @override
  T processResponseWithCustomError<T>(
    _i9.ApiResponseV2<T>? response,
    _i9.ServiceException Function(String?, int?, int?)? errorFactory,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#processResponseWithCustomError, [
              response,
              errorFactory,
            ]),
            returnValue: _i8.dummyValue<T>(
              this,
              Invocation.method(#processResponseWithCustomError, [
                response,
                errorFactory,
              ]),
            ),
          )
          as T);

  @override
  _i6.Future<T> safeApiCall<T>(_i6.Future<_i9.ApiResponseV2<T>>? apiCall) =>
      (super.noSuchMethod(
            Invocation.method(#safeApiCall, [apiCall]),
            returnValue:
                _i8.ifNotNull(
                  _i8.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#safeApiCall, [apiCall]),
                  ),
                  (T v) => _i6.Future<T>.value(v),
                ) ??
                _FakeFuture_4<T>(
                  this,
                  Invocation.method(#safeApiCall, [apiCall]),
                ),
          )
          as _i6.Future<T>);

  @override
  _i6.Future<void> safeVoidApiCall(
    _i6.Future<_i9.ApiResponseV2<void>>? apiCall,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#safeVoidApiCall, [apiCall]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  R transformData<T, R>(
    T? data,
    R Function(T)? transformer, {
    String? operationName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #transformData,
              [data, transformer],
              {#operationName: operationName},
            ),
            returnValue: _i8.dummyValue<R>(
              this,
              Invocation.method(
                #transformData,
                [data, transformer],
                {#operationName: operationName},
              ),
            ),
          )
          as R);

  @override
  void validateInput(Map<String, dynamic>? validations) => super.noSuchMethod(
    Invocation.method(#validateInput, [validations]),
    returnValueForMissingStub: null,
  );

  @override
  void validateStringField(
    String? value,
    String? fieldName, {
    int? minLength,
    int? maxLength,
    bool? required = true,
    Pattern? pattern,
    String? patternDescription,
  }) => super.noSuchMethod(
    Invocation.method(
      #validateStringField,
      [value, fieldName],
      {
        #minLength: minLength,
        #maxLength: maxLength,
        #required: required,
        #pattern: pattern,
        #patternDescription: patternDescription,
      },
    ),
    returnValueForMissingStub: null,
  );

  @override
  void validateNumericField(
    num? value,
    String? fieldName, {
    num? min,
    num? max,
    bool? required = true,
  }) => super.noSuchMethod(
    Invocation.method(
      #validateNumericField,
      [value, fieldName],
      {#min: min, #max: max, #required: required},
    ),
    returnValueForMissingStub: null,
  );

  @override
  Map<String, dynamic> processPaginationParams(
    int? pageNumber,
    int? pageSize, {
    int? maxPageSize = 100,
    int? minPageSize = 1,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #processPaginationParams,
              [pageNumber, pageSize],
              {#maxPageSize: maxPageSize, #minPageSize: minPageSize},
            ),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  void logOperation(String? operation, {Map<String, dynamic>? parameters}) =>
      super.noSuchMethod(
        Invocation.method(
          #logOperation,
          [operation],
          {#parameters: parameters},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void logError(String? operation, _i9.ServiceException? error) =>
      super.noSuchMethod(
        Invocation.method(#logError, [operation, error]),
        returnValueForMissingStub: null,
      );
}
